ojciec(kazimierz2sprawiedliwy, leszekBialy).
ojciec(kazimierz2sprawiedliwy, konrad1mazowiecki).
ojciec(konrad1mazowiecki, boleslaw).
ojciec(konrad1mazowiecki, kazimierz1).
ojciec(konrad1mazowiecki, siemowit).
ojciec(siemowit, ksiazetaMazowieccy).
ojciec(kazimierz1, leszekCzarny).
ojciec(kazimierz1, siemomysl).
ojciec(kazimierz1, wladyslaw1lokietek).
ojciec(kazimierz1, kazimierz3).
ojciec(kazimierz1, siemowit).
ojciec(siemomysl, leszek).
ojciec(siemomysl, przemysl).
ojciec(siemomysl, kazimierz3).
ojciec(kazimierz3, wladyslawBialy).
ojciec(wladyslaw1lokietek, kazimierz3wielki).
ojciec(siemowit, wladyslawGarbaty).
ojciec(siemowit, boleslaw).
syn(leszekBialy, kazimierz2sprawiedliwy).
syn(konrad1mazowiecki, kazimierz2sprawiedliwy).
syn(boleslaw, konrad1mazowiecki).
syn(kazimierz1, konrad1mazowiecki).
syn(siemowit, konrad1mazowiecki).
syn(leszekCzarny, kazimierz1).
syn(siemomysl, kazimierz1).
syn(wladyslaw1lokietek, kazimierz1).
syn(kazimierz3, kazimierz1).
syn(siemowit, kazimierz1).
syn(leszek, siemomysl).
syn(przemysl, siemomysl).
syn(kazimierz3, siemomysl).
syn(wladyslawBialy, kazimierz3).
syn(kazimierz3wielki, wladyslaw1lokietek).
syn(wladyslawGarbaty, siemowit).
syn(boleslaw, siemowit).
brat(konrad1mazowiecki, leszekBialy).
brat(konrad1mazowiecki, leszekBialy):- brat(leszekBialy, konrad1mazowiecki).
brat(boleslaw, kazimierz1).
brat(boleslaw, kazimierz1):- brat(kazimierz1, boleslaw).
brat(boleslaw, siemowit).
brat(boleslaw, siemowit):- brat(siemowit, boleslaw).
brat(kazimierz1, siemowit).
brat(kazimierz1, siemowit):- brat(siemowit, kazimierz1).
brat(leszekCzarny, siemomysl).
brat(leszekCzarny, wladyslaw1lokietek).
brat(leszekCzarny, kazimierz2).
brat(leszekCzarny, siemowit).
brat(siemomysl, wladyslaw1lokietek).
brat(siemomysl, kazimierz2).
brat(siemomysl, siemowit).
brat(wladyslaw1lokietek, kazimierz2).
brat(wladyslaw1lokietek, siemowit).
brat(kazimierz2, siemowit).
brat(leszek, przemysl).
brat(leszek, kazimierz3).
brat(przemysl, kazimierz3).
brat(wladyslawGarbaty, boleslaw).
